"""Create tables

Revision ID: a9dbb422aec1
Revises: 
Create Date: 2023-07-30 18:53:59.164245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dbb422aec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('server_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_server_rooms_id'), 'server_rooms', ['id'], unique=False)
    op.create_table('workstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_workstations_id'), 'workstations', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('cable_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socket_number', sa.Integer(), nullable=True),
    sa.Column('port_number_socket', sa.Integer(), nullable=True),
    sa.Column('port_number_patch_panel', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('workstation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_lines_employee_id'), 'cable_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_cable_lines_id'), 'cable_lines', ['id'], unique=False)
    op.create_index(op.f('ix_cable_lines_workstation_id'), 'cable_lines', ['workstation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cable_lines_workstation_id'), table_name='cable_lines')
    op.drop_index(op.f('ix_cable_lines_id'), table_name='cable_lines')
    op.drop_index(op.f('ix_cable_lines_employee_id'), table_name='cable_lines')
    op.drop_table('cable_lines')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_workstations_id'), table_name='workstations')
    op.drop_table('workstations')
    op.drop_index(op.f('ix_server_rooms_id'), table_name='server_rooms')
    op.drop_table('server_rooms')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
